# Generated by Django 3.1.4 on 2026-05-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20201212_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='courses', verbose_name='Imagen')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Cronomarcador de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Cronomarcador de modificación')),
                ('link', models.URLField(blank=True, null=True, verbose_name='link para más información')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-date'],
            },
        ),
    ]
