# Generated by Django 3.1.4 on 2026-05-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='link',
        ),
        migrations.AddField(
            model_name='course',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='courses/certificates/', verbose_name='Certificado PDF'),
        ),
    ]
