# Generated by Django 3.1.4 on 2026-05-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_auto_20201214_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon_svg', models.TextField(help_text='Pega aquí el código SVG')),
            ],
        ),
    ]
