# Generated by Django 3.1.4 on 2026-05-26 01:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Cronomarcador de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Cronomarcador de modificación'),
        ),
    ]
